### ISSUE TITLE
Feature request - use ToF sensor for dataset generator

### ISSUE THREAD

**Issue by lvonasek** [FilippoAleotti/OMA#2]
You can find an app using ToF sensor on Huawei P30 Pro and Honor View 20 here:
https://github.com/mpottinger/arcoreDepth_example

**Comment by bartn8** [comment]
Hi. Need a week.
Please ne patient

**Comment by bartn8** [comment]
Hi @lvonasek 
Now ToF sensor is used for additional dataset generation.
Data is saved under tof folder as json.
I don't tested it because I don't have a smartphone with a ToF sensor.

**Comment by lvonasek** [comment]
Thank you, it did not work but I fixed it by #3. Shall I record a ToF dataset for you?

**Comment by bartn8** [comment]
Yes, thanks. I am curious.

**Comment by lvonasek** [comment]
https://drive.google.com/file/d/1MZeLI3_3juqMW_EyODI075xbxl470_NA/view?usp=drivesdk

If the format is correct then I could record bigger dataset for the Tensor flow model training... Give me know

**Comment by bartn8** [comment]
Thank you very much.
So far, the dataset you generated is enough.
Probably, i will make a script to generate depth plasma image from ToF dataset.
Best regards.
